# Generated by Django 4.2.21 on 2025-05-29 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the search session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the search session')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Review'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('ERROR', 'Error')], default='DRAFT', help_text='Current status of the search session', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this session was last updated')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this session was started', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='When this session was completed', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this search session', on_delete=django.db.models.deletion.PROTECT, related_name='search_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Session',
                'verbose_name_plural': 'Search Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Session Created'), ('STATUS_CHANGED', 'Status Changed'), ('MODIFIED', 'Session Modified'), ('COMMENT', 'Comment Added'), ('ERROR', 'Error Occurred'), ('SYSTEM', 'System Event')], help_text='Type of activity recorded', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('old_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Review'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('ERROR', 'Error')], help_text='Previous status (for status changes)', max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Review'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('ERROR', 'Error')], help_text='New status (for status changes)', max_length=20, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='When this activity occurred')),
                ('metadata', models.JSONField(blank=True, help_text='Additional structured data about the activity', null=True)),
                ('performed_by', models.ForeignKey(help_text='User who performed this activity', on_delete=django.db.models.deletion.PROTECT, related_name='session_activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The search session this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='review_manager.searchsession')),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'ordering': ['-performed_at'],
            },
        ),
    ]
