# Generated by Django 4.2.21 on 2025-05-29 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permission settings (Phase 2 feature)'),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='private', help_text='Who can view this session (Phase 2 feature)', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this search session', on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When this session was started (moved beyond draft)', null=True),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('strategy_ready', 'Strategy Ready'), ('executing', 'Executing Searches'), ('processing', 'Processing Results'), ('ready_for_review', 'Ready for Review'), ('in_review', 'Under Review'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', help_text='Current status of the search session', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='title',
            field=models.CharField(help_text='Title of the search session', max_length=200),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Session Created'), ('STATUS_CHANGED', 'Status Changed'), ('MODIFIED', 'Session Modified'), ('STRATEGY_DEFINED', 'Search Strategy Defined'), ('SEARCH_EXECUTED', 'Search Executed'), ('RESULTS_PROCESSED', 'Results Processed'), ('REVIEW_STARTED', 'Review Started'), ('REVIEW_COMPLETED', 'Review Completed'), ('COMMENT', 'Comment Added'), ('ERROR', 'Error Occurred'), ('SYSTEM', 'System Event')], help_text='Type of activity recorded', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='new_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('strategy_ready', 'Strategy Ready'), ('executing', 'Executing Searches'), ('processing', 'Processing Results'), ('ready_for_review', 'Ready for Review'), ('in_review', 'Under Review'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], help_text='New status (for status changes)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='old_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('strategy_ready', 'Strategy Ready'), ('executing', 'Executing Searches'), ('processing', 'Processing Results'), ('ready_for_review', 'Ready for Review'), ('in_review', 'Under Review'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], help_text='Previous status (for status changes)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['created_by', 'status'], name='review_mana_created_ff6ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['created_at'], name='review_mana_created_75de23_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['updated_at'], name='review_mana_updated_a3db28_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['status'], name='review_mana_status_03aa17_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', 'performed_at'], name='review_mana_session_cd49d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['activity_type', 'performed_at'], name='review_mana_activit_82a210_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['performed_by', 'performed_at'], name='review_mana_perform_f9576b_idx'),
        ),
        # Removed problematic CheckConstraint - title validation handled at form level
    ]
