# Generated by Django 4.2.21 on 2025-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_manager', '0001_initial_with_uuids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Session Activity', 'verbose_name_plural': 'Session Activities'},
        ),
        migrations.RemoveIndex(
            model_name='sessionactivity',
            name='review_mana_session_cd49d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionactivity',
            name='review_mana_activit_82a210_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionactivity',
            name='review_mana_perform_f9576b_idx',
        ),
        migrations.RenameField(
            model_name='sessionactivity',
            old_name='performed_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='sessionactivity',
            old_name='performed_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='sessionactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='sessionactivity',
            name='metadata',
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='action',
            field=models.CharField(default='SYSTEM', help_text='Type of activity recorded', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured data about the activity'),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the activity'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', 'timestamp'], name='review_mana_session_582e50_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['action', 'timestamp'], name='review_mana_action_4fc964_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['user', 'timestamp'], name='review_mana_user_id_48c62f_idx'),
        ),
    ]
